### ISSUE TITLE
Bug Virtualan does not get correct dataset

### ISSUE THREAD

**Issue by networkinss** [virtualansoftware/virtualan#325]
I posted a dataset, but cannot retrieve it.

curl --location --request GET 'https://live.virtualandemo.com/api/persons/hfrüh'

Instead it gives me the data for "bgates".

**Comment by elans3** [comment]
@networkinss it is due to that Script mock data was set to default for any request. Refer record 9 in mock data for more details.

**Comment by elans3** [comment]
The order of Mock data selection happens this way.
1) Rule takes precedence
2) Script takes 2 in order takes precedence
3) then Static/Parameter mock response takes precedence

**Comment by networkinss** [comment]
The default script is not visible and therefore leads to confusion.
Would be good to have that transparent like with an overview of the scripts.

**Comment by elans3** [comment]
That option not available right now.
