### ISSUE TITLE
Unescaped control character error

### ISSUE THREAD

**Issue by 4ndris** [virtualansoftware/virtualan#328]
# Description

I have mock responses defined with `virtualan-plugin`. These mock responses are created with virtualan UI on the Add Mock screen, for OpenAPI specification that was used to generate virtual APIs in my application. 

Mock responses are added successfully, mock responses can be retrieves successfully in the Overall Catalog, with `virtual-service-controller` and the `[GET] /virtualservices` - listAllMockLoadRequests.  

Example:
![image](https://user-images.githubusercontent.com/4981509/156373183-9b882f62-04b7-4e0e-a878-95ac3720ac2d.png)

As you can see the mock response stored formatted with  e.g. `\n` white space characters.
The issue is that when a client calls this endpoint the mock response will return 'as is' and for example in Jackson parser this will trigger an unescaped control character error.  

Would it be possible to remove these special characters when you store it and only perform formatting on the UI when you display the JSON content?

**Comment by elans3** [comment]
This issue addressed in version 2.5.1. 
- Select content type as JSON which creating a mock.
- which would return/represent input and output values in the JSON Format.
Please try and let me know

**Comment by 4ndris** [comment]
@elans3 
Great news, we are in progress with the tests. I get back to you once we are done. In meantime I see that the menu item "Overall catalog" opens PetStore definition instead Virtualan api catalog. Have you faced this issue before?

![image](https://user-images.githubusercontent.com/4981509/157703106-375d3590-6ceb-483b-8c19-8a36b9bdb647.png)

**Comment by elans3** [comment]
In virtualan, springdoc.swagger-ui.queryConfigEnabled is enabled by default. which is causing the issue.
See if the below example helps?
https://github.com/virtualansoftware/service-virtualization-openapi/blob/master/src/main/java/io/virtualan/DisableSpringDocQueryParameter.ja

**Comment by 4ndris** [comment]
> This issue addressed in version 2.5.1.
> 
> * Select content type as JSON while creating a mock.
> * Which would return input and output as JSON.
>   Can you validate and confirm

fyi, we see it works fine (y) thank you for the enhancement

**Comment by elans3** [comment]
Thank you @4ndris..  We will update Overall URL in next release.
